// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRbhYVPWXF4KSRFP_hqjmftbwwYYpNJ0',
    appId: '1:781363468537:web:3f0b433fa6f5e84ebf2a28',
    messagingSenderId: '781363468537',
    projectId: 'tales_space-9bc94',
    authDomain: 'tales_space-9bc94.firebaseapp.com',
    storageBucket: 'tales_space-9bc94.appspot.com',
    measurementId: 'G-H7B2PLQM9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB9njuebunZkMFKAcoTGjTBJCVhATLtnQ',
    appId: '1:781363468537:android:cc279ac13cb7971abf2a28',
    messagingSenderId: '781363468537',
    projectId: 'tales_space-9bc94',
    storageBucket: 'tales_space-9bc94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR5WDP1HCkdoiiAqg3UDMpEfDhh4m4ojo',
    appId: '1:781363468537:ios:86383d88bcdfa09ebf2a28',
    messagingSenderId: '781363468537',
    projectId: 'tales_space-9bc94',
    storageBucket: 'tales_space-9bc94.appspot.com',
    iosBundleId: 'com.interesting.tales_space',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR5WDP1HCkdoiiAqg3UDMpEfDhh4m4ojo',
    appId: '1:781363468537:ios:86383d88bcdfa09ebf2a28',
    messagingSenderId: '781363468537',
    projectId: 'tales_space-9bc94',
    storageBucket: 'tales_space-9bc94.appspot.com',
    iosBundleId: 'com.interesting.tales_space',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsRbhYVPWXF4KSRFP_hqjmftbwwYYpNJ0',
    appId: '1:781363468537:web:48e3223fb5d5aee6bf2a28',
    messagingSenderId: '781363468537',
    projectId: 'tales_space-9bc94',
    authDomain: 'tales_space-9bc94.firebaseapp.com',
    storageBucket: 'tales_space-9bc94.appspot.com',
    measurementId: 'G-K5FJDWBXLJ',
  );
}
