// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rXWbtKlbungETlI-9f5O7dQz5EpHpCM',
    appId: '1:743810771963:web:f7cd8b961cd4a7221b395e',
    messagingSenderId: '743810771963',
    projectId: 'tales-space',
    authDomain: 'tales-space.firebaseapp.com',
    storageBucket: 'tales-space.firebasestorage.app',
    measurementId: 'G-TJ9HTD0WV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy6ecl1LJ4dNb-hKptlUtJTH0NKWQVpoE',
    appId: '1:743810771963:android:78c93c1bef9f3b4d1b395e',
    messagingSenderId: '743810771963',
    projectId: 'tales-space',
    storageBucket: 'tales-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLYDZVyQC5KMUR7snTt63fmIWhNuYPF4',
    appId: '1:743810771963:ios:65e0ebe4bbe0c1261b395e',
    messagingSenderId: '743810771963',
    projectId: 'tales-space',
    storageBucket: 'tales-space.firebasestorage.app',
    iosClientId: '743810771963-1tuen4fjblflhsk0m2a6s9msofkoce82.apps.googleusercontent.com',
    iosBundleId: 'com.tales.talesSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLYDZVyQC5KMUR7snTt63fmIWhNuYPF4',
    appId: '1:743810771963:ios:65e0ebe4bbe0c1261b395e',
    messagingSenderId: '743810771963',
    projectId: 'tales-space',
    storageBucket: 'tales-space.firebasestorage.app',
    iosClientId: '743810771963-1tuen4fjblflhsk0m2a6s9msofkoce82.apps.googleusercontent.com',
    iosBundleId: 'com.tales.talesSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3rXWbtKlbungETlI-9f5O7dQz5EpHpCM',
    appId: '1:743810771963:web:4d7570c0b0980f811b395e',
    messagingSenderId: '743810771963',
    projectId: 'tales-space',
    authDomain: 'tales-space.firebaseapp.com',
    storageBucket: 'tales-space.firebasestorage.app',
    measurementId: 'G-LL1NNG5EVS',
  );

}